services:
  Db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: fr_login
      POSTGRES_PASSWORD: fr_pass
      POSTGRES_Db: fr_Db
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initDb.d
      - fr-Db-data:/var/lib/postgresql/data
    ports:
      - "5050:5432"

volumes:
  fr-Db-data: